### ISSUE TITLE
OSError:  No such file or directory

### ISSUE THREAD

**Issue by mpkuse** [Zulko/vapory#27]
I could install vapory. I tried the example you gave.

from vapory import *

camera = Camera( 'location', [0,2,-3], 'look_at', [0,1,2] )
light = LightSource( [2,4,-3], 'color', [1,1,1] )
sphere = Sphere( [0,1,2], 2, Texture( Pigment( 'color', [1,0,1] )))

scene = Scene( camera, objects= [light, sphere])
scene.render("purple_sphere.png", width=400, height=300)

scene.render() call fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/vapory/vapory.py", line 102, in render
    quality, antialiasing, remove_temp)
  File "/usr/local/lib/python2.7/dist-packages/vapory/io.py", line 106, in render_povstring
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Any pointers?

**Comment by giovannicaprio** [comment]
I have the same problem...

**Comment by momonala** [comment]
Were you able to solve this? I just installed Vapory and am getting this issue as well. I saw you posted a more advanced issue so I'm assuming you've figured this out?

**Comment by PiscesDream** [comment]
Same problem on Ubuntu 16.06.

**Comment by kpngwenya** [comment]
Same problem on Windows 10 Python3. Thought I was the only one.

**Comment by ziyi-yang** [comment]
Hi,
I solve by I editing the config.py as follows:
POVRAY_BINARY = path/to/povray/binary

https://github.com/Zulko/vapory/issues/18

**Comment by ImaneFerradj** [comment]
Hi ! I am having the same issue on Windows 10, where is the file config.py pls?
