### ISSUE TITLE
add numpy to requirements

### ISSUE THREAD

**Issue by deanmalmgren** [Zulko/vapory#44]
In trying to run the `./examples/cube.py`, I got an error about trying to import `numpy`:

```
Traceback (most recent call last):
  File "legos.py", line 4, in <module>
    import vapory
  File "/Users/rdm/.virtualenvs/lego-construction/lib/python3.6/site-packages/vapory/__init__.py", line 4, in <module>
    from .vapory import *
  File "/Users/rdm/.virtualenvs/lego-construction/lib/python3.6/site-packages/vapory/vapory.py", line 4, in <module>
    from .io import render_povstring
  File "/Users/rdm/.virtualenvs/lego-construction/lib/python3.6/site-packages/vapory/io.py", line 11, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

I'm not entirely sure numpy is needed, but if it is, it should be listed in the `setup.py`.

**Comment by maryito** [comment]
Hi managed to solve by installing numpy through pip
` pip install numpy`

**Comment by NGeorgescu** [comment]
Ah looks like the code has an `except` for an `IOError` but not for a `ModuleNotFoundError`.

**Comment by NGeorgescu** [comment]
This issue has been fixed. If you import the library without numpy it works but if you need numpy for the particular function only then will it stop you.
